# Site settings
title: Reconnecting with Coding
header-img: img/home-bg.png
email: lvalmoria@gmail.com
copyright_name: lvalmoria
description: > # this means to ignore newlines until "baseurl:"
  One page at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: luminescher
github_username:  lvalmoria
learn_profile: lvalmoria
email_username: lvalmoria@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
